name: '${pluginName}'
version: '${version}'
main: '${group}.${packageName}.Main'
api-version: '${paperVersion}'
commands:
libraries:
  ${pluginLibraries}
  - io.github.monun:kommand-core:3.1.7
  - io.github.monun:tap-core:4.9.8
  - io.github.monun:invfx-core:3.3.2